import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { cn } from '@/shared/lib/utils'

import './globals.css'

const fontExcalidraw = localFont({
  src: '../shared/assets/fonts/Excalifont-Regular.woff2',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={cn('h-full', 'antialiased', fontExcalidraw.className)}
    >
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  )
}
